Devblocks.remove({})
Devblocks.insert({client: "ITW",date: new Date(2014,6,1),img: "invent_logo.png",link:"http://inventtheworld.com.au"})
Devblocks.insert({client: "ITW",date: new Date(2014,10,1),img: "invent_logo.png",link:"http://inventtheworld.com.au"})
Devblocks.insert({client: "ITW",date: new Date(2015,0,1),img: "invent_logo.png",link:"http://inventtheworld.com.au"})
Devblocks.insert({client: 0,date: new Date(2015,2,1)})
Devblocks.insert({client: "Broadstories",date: new Date(2015,3,1),img: "broadstories.png",link:"http://broadstories.com"})
Devblocks.insert({client: 0,date: new Date(2015,4,1)})
Devblocks.insert({client: "Private Client",date: new Date(2015,5,1),img: "invent_logo.png",link:"http://inventtheworld.com.au"})
Devblocks.insert({client: "ITW",date: new Date(2015,6,1)})
Devblocks.insert({client: 0,date: new Date(2015,7,1)})
Devblocks.insert({client: 0,date: new Date(2015,8,1)})
Devblocks.insert({client: 0,date: new Date(2015,9,1)})
Devblocks.insert({client: "Private Client",date: new Date(2015,10,1)})
Devblocks.insert({client: 0,date: new Date(2015,11,1)})
Devblocks.insert({client: 0,date: new Date(2016,0,1)})
Devblocks.insert({client: 0,date: new Date(2016,1,1)})
Devblocks.insert({client: 0,date: new Date(2016,2,1)})
Devblocks.insert({client: 0,date: new Date(2016,3,1)})
Devblocks.insert({client: 0,date: new Date(2016,4,1)})
Devblocks.insert({client: 0,date: new Date(2016,5,1)})
Devblocks.insert({client: 0,date: new Date(2016,6,1)})
Devblocks.insert({client: 0,date: new Date(2016,7,1)})
